criterion:
  name: ce

optimizer:
  name: adamw
  lr: 0.002
  weight_decay: 0.0001

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0

run:
  experiment: "default"
  n_epochs: 100
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  random_state: 42
  log_interval: 200
  train_noise: 0

quantize:
  weight_bit: 32
  input_bit: 32
  pad_max: 1

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "cifar10/resnet20/train"
  model_comment: ""
  resume: 0
  restore_checkpoint: ""
  no_linear: 0

model:
  name: "DPE_ResNet20"
  dpe:
    name: "DPE"
    n_ports: 5
    n_pads: 5
    hidden_dims: [256, 256, 128, 128, 128]
    act_cfg:
      type: GELU
    dropout_rate: 0.15
    drop_path_rate: 0.0
    norm: bn
    with_cp: False
    dpe_noise_ratio: 0
    checkpoint: ""
debug:
  verbose: 1

