
criterion:
  name: cmae

optimizer:
  name: adam
  lr: 0.004
  weight_decay: 0.00001

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0.00001

run:
  experiment: "mmi_dpe_pretrain"
  n_epochs: 400
  batch_size: 16
  amp: False

quantize:
  weight_bit: 32
  input_bit: 32

checkpoint:
  save_best_model_k: 1
  checkpoint_dir: "mmi/dpe/pretrain"
  model_comment: ""
  resume: 0
  restore_checkpoint: ""
  no_linear: 0

model:
  name: "DPE"
  dropout_rate: 0.2

debug:
  verbose: 1

