dataset:
  name: cifar10
  root: "./data"
  num_workers: 2
  img_height: 32
  img_width: 32
  train_valid_split_ratio: [0.9, 0.1]
  center_crop: 32
  resize_mode: bicubic
  n_test_samples: null
  n_valid_samples: null
  in_channels: 3
  num_classes: 10
  transform: basic
  shuffle: 1
  augment: null
  test_augment: null

dpe_dataset:
  name: mmi
  root: "./data"
  num_workers: 2
  train_valid_split_ratio: [1, 0]
  center_crop: null
  resize_mode: bicubic
  n_test_samples: null
  n_valid_samples: null
  test_ratio: 0.2
  in_channels: 4
  num_classes: 10
  transform: basic
  shuffle: 1
  file_list: ["port_5_res_4_range_0.03"]
  processed_dir: port_5_res_4_0.03
  augment: null
  test_augment: null

criterion:
  name: ce

aux_criterion:
  kl_distill:
    weight: 0.1

optimizer:
  name: adamw
  lr: 0.002
  weight_decay: 0.0001

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0

run:
  experiment: "default"
  n_epochs: 100
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  random_state: 42
  log_interval: 200
  train_noise: 0
  grad_clip: False
  max_grad_value: 1
  do_distill: False

quantize:
  weight_bit: 8
  input_bit: 8
  pad_max: 1

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "cifar10/resnet20/train"
  model_comment: ""
  resume: 0
  restore_checkpoint: ""
  no_linear: 0

teacher:
  name: "ResNet20"
  act_cfg:
    type: ReLU
    inplace: True
  checkpoint: ""
  norm: bn
  
model:
  name: "DPE_ResNet20"
  block_list: [5, 5, 5]
  n_pads: 5
  sigma_trainable: False
  act_cfg:
    type: ReLU6
    inplace: True
  norm: bn
  dpe: null
  mode: usv
  path_multiplier: 2
  unfolding: True
   
debug:
  verbose: 1
